# Generated by Django 5.1.3 on 2024-11-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDesk', '0003_alter_tickets_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ubicacion',
            field=models.CharField(choices=[('Central', 'Central'), ('Pacifico', 'Pacifico'), ('Tortugas', 'Tortugas'), ('Aldrey', 'Aldrey'), ('Avellaneda', 'Avellaneda'), ('Alcorta', 'Alcorta'), ('Solar', 'Solar'), ('Village', 'Village'), ('DOT', 'DOT'), ('Nordelta', 'Nordelta'), ('Palermo', 'Palermo'), ('Unicenter', 'Unicenter'), ('47Abasto', 'Abasto'), ('47Soleil', 'Soleil'), ('47Arcos', 'Arcos'), ('47Flores', 'Flores'), ('47Florida', 'Florida'), ('47Soho', 'Soho'), ('47Salta', 'Salta'), ('47Palmas', 'Palmas'), ('47Pinamar', 'Pinamar'), ('47Lomitas', 'Lomitas'), ('MichDot', 'MichDot')], max_length=20),
        ),
    ]
