# Generated by Django 5.1.3 on 2024-11-14 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDesk', '0005_tickets_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('AB', 'Abierto'), ('EN', 'En atención'), ('ES', 'Esperando 3ro'), ('DU', 'Duplicado'), ('RE', 'Resuelto'), ('CE', 'Cerrado')], default='AB', max_length=2)),
                ('prioridad', models.CharField(choices=[('BA', 'Baja'), ('ME', 'Media'), ('AL', 'Alta')], default='BA', max_length=2)),
                ('ubicacion', models.CharField(choices=[('Central', 'Central'), ('Pacifico', 'Pacifico'), ('Tortugas', 'Tortugas'), ('Aldrey', 'Aldrey'), ('Avellaneda', 'Avellaneda'), ('Alcorta', 'Alcorta'), ('Solar', 'Solar'), ('Village', 'Village'), ('DOT', 'DOT'), ('Nordelta', 'Nordelta'), ('Palermo', 'Palermo'), ('Unicenter', 'Unicenter'), ('47Abasto', 'Abasto'), ('47Soleil', 'Soleil'), ('47Arcos', 'Arcos'), ('47Flores', 'Flores'), ('47Florida', 'Florida'), ('47Soho', 'Soho'), ('47Salta', 'Salta'), ('47Palmas', 'Palmas'), ('47Pinamar', 'Pinamar'), ('47Lomitas', 'Lomitas'), ('MichDot', 'MichDot')], max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='HelpDesk.ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
