# Generated by Django 5.1.3 on 2024-11-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDesk', '0006_ticket_comentario_delete_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('AB', 'Abierto'), ('EN', 'En atención'), ('ES', 'Esperando 3ro'), ('CE', 'Cerrado')], default='AB', max_length=2),
        ),
    ]
