# Generated by Django 5.1.3 on 2024-11-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDesk', '0008_horastrabajos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HorasTrabajos',
        ),
    ]
